version: "2"
services:
   datanode:
      image: apache/hadoop:3
      command: ["hdfs", "datanode"]
      env_file:
        - ./config
      ports:
        - 50075:50075
        - 50475:50475
        - 50010:50010
        - 50020:50020


   nodemanager:
      image: apache/hadoop:3
      command: ["yarn", "nodemanager"]
      env_file:
        - ./config
